# Generated by Django 2.0.7 on 2018-07-31 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newspaper_wordandcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsPaper',
        ),
    ]
